name: test_honours
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project

  cupertino_icons: ^1.0.2 # Only required if you use Cupertino (iOS style) icons
  material_design_icons_flutter: 6.0.7096
  firebase_auth: ^4.2.4
  firebase_core:
  google_sign_in:
  get:
  syncfusion_flutter_calendar: 20.3.56
  http: ^0.13.5
  table_calendar: ^3.0.6
  intl: ^0.17.0
  provider: ^6.0.3
  mockito: ^5.0.17
  flutter_screenutil: 5.6.1
  json_annotation: 4.8.0
  cloud_firestore: ^4.4.2
  toggle_switch: ^2.0.1
  weight_slider: ^1.2.2
  height_slider: ^1.3.2
  custom_navigation_bar: ^0.8.2
  email_validator: ^2.1.17
  image_picker: ^0.8.6+2
  permission_handler: ^10.2.0
  firebase_database: ^10.0.11
  firebase_storage: ^11.0.13
  intl_phone_field: ^3.1.0
  firestore_ui: ^1.25.1
  url_launcher: ^6.1.10



dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests

flutter:

  uses-material-design: true # Required if you use the Material icon font

  assets:  # Lists assets, such as image files
    - img/app_login_page_logo.png
    - img/blue-btn.png
    # - img/f.png
    # - img/facebook_logo.png
    # - img/gmail_logo.png
    - img/login_avatar.png
    - img/sign_in.jpg
    - img/doctors/doc1.jpg
    - img/doctors/doc2.jpg
    - img/doctors/doc3.jpg
    - img/doctors/doc4.jpg

#
#  fonts:              # Required if your app uses custom fonts
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700